version: "3.3"

services:
  redis:
    image: redis:6.2.4-alpine3.13
    restart: unless-stopped
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data